version: '3'
services:
  web:
    image: nginx:latest
    restart: on-failure
    ports:
     - "9000:80"
    volumes:
        - ./app:/application
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  app:
    build: ./
    restart: on-failure
    environment:
      DEBUG: 'true'      
    volumes:
      - ./app:/application   
networks:
    default:
        driver: bridge
        ipam:
            driver: default